#!/bin/bash

if /bin/launchctl list "com.webmeshproj.webmeshd" &> /dev/null ; then
  /bin/launchctl unload /Library/LaunchDaemons/com.webmeshproj.webmeshd.plist
fi

rm -f /Library/LaunchDaemons/com.webmeshproj.webmeshd.plist
